[tool.poetry]
name = "gestion_planing"
version = "0.1.0"
description = ""
authors = ["Charbel AHOUANDOKOUN","Nazifou Afolabi"]
readme = "README.md"
packages = [{include = "gestion_planing"}]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.28.2"
networkx = "^3.1"
json5 = "^0.9.11"


[tool.poetry.group.dev.dependencies]
rich = "^13.3.4"
pytest = "^7.3.1"
black = "^23.3.0"
ruff = "^0.0.261"
mypy = "^1.2.0"
typer = "^0.7.0"
pytest-cov = "^4.0.0"
pylama = "^8.4.1"
coverage = "^7.2.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
